-- ====================================================
-- Course Visual Generation Platform - Database Schema
-- ====================================================
-- This migration creates a DENORMALIZED schema where:
-- - course_name is the business identifier (instead of UUIDs)
-- - prompt_json stores the ENTIRE storyboard as JSONB
-- - NO JSON querying in SQL (all traversal in Python)
-- ====================================================

-- Drop existing tables (in reverse dependency order)
DROP TABLE IF EXISTS prompts CASCADE;
DROP TABLE IF EXISTS frames CASCADE;
DROP TABLE IF EXISTS shots CASCADE;
DROP TABLE IF EXISTS videos CASCADE;
DROP TABLE IF EXISTS generation_jobs CASCADE;
DROP TABLE IF EXISTS files CASCADE;
DROP TABLE IF EXISTS images CASCADE;

-- ====================================================
-- 1) FILES TABLE
-- ====================================================
-- Business identifier: course_name (immutable, unique)
-- Stores the uploaded file's extracted text content

CREATE TABLE files (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    course_name TEXT NOT NULL UNIQUE,
    full_text TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE files IS 'Stores uploaded course files with course_name as unique business identifier';
COMMENT ON COLUMN files.course_name IS 'Immutable business identifier - used across all tables';
COMMENT ON COLUMN files.full_text IS 'Extracted plain text from uploaded file (.pdf, .docx, .txt)';

-- ====================================================
-- 2) PROMPTS TABLE
-- ====================================================
-- Stores the ENTIRE storyboard structure as a single JSONB object
-- NO normalization - all videos/shots/frames stored in one JSON

CREATE TABLE prompts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    course_name TEXT NOT NULL REFERENCES files(course_name) ON DELETE CASCADE,
    prompt_json JSONB NOT NULL,
    model_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE prompts IS 'Stores AI-generated storyboard prompts as single JSONB object';
COMMENT ON COLUMN prompts.prompt_json IS 'Full storyboard structure: {videos: [{shots: [{frames: [...]}]}]}';
COMMENT ON COLUMN prompts.model_name IS 'AI model used for generation (e.g., gpt-4o-mini)';

-- ====================================================
-- 3) IMAGES TABLE
-- ====================================================
-- Stores generated images with frame_code as lookup key
-- frame_code format: "V1_S2_F3" (Video 1, Shot 2, Frame 3)

CREATE TABLE images (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    course_name TEXT NOT NULL REFERENCES files(course_name) ON DELETE CASCADE,
    frame_code TEXT NOT NULL,
    image_url TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(course_name, frame_code)
);

COMMENT ON TABLE images IS 'Stores generated images for each frame';
COMMENT ON COLUMN images.frame_code IS 'Lookup key format: V1_S2_F3 (Video 1, Shot 2, Frame 3)';
COMMENT ON COLUMN images.image_url IS 'URL to generated image (Higgsfield AI)';

-- ====================================================
-- 4) VIDEOS TABLE
-- ====================================================
-- Stores final generated videos

CREATE TABLE videos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    course_name TEXT NOT NULL REFERENCES files(course_name) ON DELETE CASCADE,
    video_number INTEGER NOT NULL,
    video_url TEXT,
    script_clean TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(course_name, video_number)
);

COMMENT ON TABLE videos IS 'Stores final generated videos';
COMMENT ON COLUMN videos.video_number IS 'Video sequence number (1, 2, 3, ...)';
COMMENT ON COLUMN videos.script_clean IS 'Cleaned script generated by OpenAI';
COMMENT ON COLUMN videos.video_url IS 'URL to final generated video (Higgsfield AI)';

-- ====================================================
-- INDEXES FOR PERFORMANCE
-- ====================================================

CREATE INDEX idx_prompts_course_name ON prompts(course_name);
CREATE INDEX idx_images_course_name ON images(course_name);
CREATE INDEX idx_images_frame_code ON images(course_name, frame_code);
CREATE INDEX idx_videos_course_name ON videos(course_name);
CREATE INDEX idx_videos_video_number ON videos(course_name, video_number);

-- ====================================================
-- DATABASE RULES (ENFORCED)
-- ====================================================
-- ✅ course_name is the business identifier across the system
-- ✅ course_name is immutable after creation
-- ✅ Relational integrity enforced using FOREIGN KEYS
-- ✅ prompt_json stored as single JSONB object (no normalization)
-- ✅ NO JSON querying inside SQL allowed
-- ====================================================
